version: '2'

services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - "8080:8080"
    external_links:
      - neo4j

networks:
  default:
    external:
      name: nw_cheminot
