#!/bin/bash

CONF_PATH=/etc/neo4j/neo4j-server.properties
PORT=7474
DIR="/data"
AUTH="false"
HTTPS="false"

while [[ $# -gt 1 ]]
do
    key="$1"

    case $key in
        -p|--port)
            PORT="$2"
            shift
            ;;

        -p|--path)
            DIR="$2"
            shift
            ;;

        -a|--auth)
            AUTH="$2"
            shift
            ;;

        -s|--https)
            HTTPS="$2"
            shift
            ;;
        *)
            ;;
    esac
    shift
done

cp /etc/neo4j/neo4j-server.properties neo4j-server.properties.bk

awk -F"=" -v value="$PORT" 'BEGIN {OFS="=";} /org.neo4j.server.webserver.port/{$2=value;print;next}1' neo4j-server.properties.bk > $CONF_PATH

cp /etc/neo4j/neo4j-server.properties neo4j-server.properties.bk

awk -F"=" -v value="$DIR" 'BEGIN {OFS="=";} /org.neo4j.server.database.location/{$2=value;print;next}1' neo4j-server.properties.bk > $CONF_PATH

cp /etc/neo4j/neo4j-server.properties neo4j-server.properties.bk

awk -F"=" -v value="$AUTH" 'BEGIN {OFS="=";} /dbms.security.auth_enabled/{$2=value;print;next}1' neo4j-server.properties.bk > $CONF_PATH

cp /etc/neo4j/neo4j-server.properties neo4j-server.properties.bk

awk -F"=" -v value="$HTTPS" 'BEGIN {OFS="=";} /org.neo4j.server.webserver.https.enabled/{$2=value;print;next}1' neo4j-server.properties.bk > $CONF_PATH

rm neo4j-server.properties.bk

echo "org.neo4j.server.webserver.address=0.0.0.0" >> $CONF_PATH

cat $CONF_PATH

/var/lib/neo4j/bin/neo4j console
