version: '2'

services:
  db:
    container_name: neo4j
    build:
      context: .
    ports:
      - "7474:7474"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    cpuset: 0,8

networks:
  default:
    external:
      name: nw_cheminot
